// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear
//
// AArch64-specific CPU feature detection and CPU id implementation.
//
// This file structure and design patterns are derived from the x86 CPU
// feature detection system originally developed by Intel Corporation and
// generated by scripts/x86simd_generate.pl (Copyright 2022-2025 Intel
// Corporation, Apache-2.0 license).
//
// NOTE: this file is copied to <build directory>/framework/device/cpu/cpu_features.h

#ifndef INC_CPU_FEATURES_AARCH64_H
#define INC_CPU_FEATURES_AARCH64_H

#include <stddef.h>      // size_t, NULL
#include <stdint.h>

// AArch64 CPU Feature Detection
// Features detected via Linux HWCAP/HWCAP2 from getauxval(AT_HWCAP/AT_HWCAP2)
//
// Layout:
//   device_features_t bits 0-63:   HWCAP bits 0-63
//   device_features_t bits 64-127: HWCAP2 bits 0-63

typedef unsigned __int128 device_features_t;
#define CPU_FEATURE_CONSTANT(bit) (((device_features_t) 1) << (bit))

// HWCAP features (bits 0-31)
#define cpu_feature_fp                             (CPU_FEATURE_CONSTANT(0))
#define cpu_feature_asimd                          (CPU_FEATURE_CONSTANT(1))
#define cpu_feature_neon                           cpu_feature_asimd  // Alias
#define cpu_feature_evtstrm                        (CPU_FEATURE_CONSTANT(2))
#define cpu_feature_aes                            (CPU_FEATURE_CONSTANT(3))
#define cpu_feature_pmull                          (CPU_FEATURE_CONSTANT(4))
#define cpu_feature_sha1                           (CPU_FEATURE_CONSTANT(5))
#define cpu_feature_sha2                           (CPU_FEATURE_CONSTANT(6))
#define cpu_feature_crc32                          (CPU_FEATURE_CONSTANT(7))
#define cpu_feature_atomics                        (CPU_FEATURE_CONSTANT(8))
#define cpu_feature_lse                            cpu_feature_atomics  // Alias
#define cpu_feature_fphp                           (CPU_FEATURE_CONSTANT(9))
#define cpu_feature_asimdhp                        (CPU_FEATURE_CONSTANT(10))
#define cpu_feature_fp16                           (cpu_feature_fphp | cpu_feature_asimdhp)
#define cpu_feature_cpuid                          (CPU_FEATURE_CONSTANT(11))
#define cpu_feature_asimdrdm                       (CPU_FEATURE_CONSTANT(12))
#define cpu_feature_jscvt                          (CPU_FEATURE_CONSTANT(13))
#define cpu_feature_fcma                           (CPU_FEATURE_CONSTANT(14))
#define cpu_feature_lrcpc                          (CPU_FEATURE_CONSTANT(15))
#define cpu_feature_dcpop                          (CPU_FEATURE_CONSTANT(16))
#define cpu_feature_sha3                           (CPU_FEATURE_CONSTANT(17))
#define cpu_feature_sm3                            (CPU_FEATURE_CONSTANT(18))
#define cpu_feature_sm4                            (CPU_FEATURE_CONSTANT(19))
#define cpu_feature_asimddp                        (CPU_FEATURE_CONSTANT(20))
#define cpu_feature_dotprod                        cpu_feature_asimddp  // Alias
#define cpu_feature_sha512                         (CPU_FEATURE_CONSTANT(21))
#define cpu_feature_sve                            (CPU_FEATURE_CONSTANT(22))
#define cpu_feature_asimdfhm                       (CPU_FEATURE_CONSTANT(23))
#define cpu_feature_dit                            (CPU_FEATURE_CONSTANT(24))
#define cpu_feature_uscat                          (CPU_FEATURE_CONSTANT(25))
#define cpu_feature_ilrcpc                         (CPU_FEATURE_CONSTANT(26))
#define cpu_feature_flagm                          (CPU_FEATURE_CONSTANT(27))
#define cpu_feature_ssbs                           (CPU_FEATURE_CONSTANT(28))
#define cpu_feature_sb                             (CPU_FEATURE_CONSTANT(29))
#define cpu_feature_paca                           (CPU_FEATURE_CONSTANT(30))
#define cpu_feature_pacg                           (CPU_FEATURE_CONSTANT(31))

// Extended HWCAP features (bits 32-47)
#define cpu_feature_gcs                            (CPU_FEATURE_CONSTANT(32))
#define cpu_feature_cmpbr                          (CPU_FEATURE_CONSTANT(33))
#define cpu_feature_fprcvt                         (CPU_FEATURE_CONSTANT(34))
#define cpu_feature_f8mm8                          (CPU_FEATURE_CONSTANT(35))
#define cpu_feature_f8mm4                          (CPU_FEATURE_CONSTANT(36))
#define cpu_feature_sve_f16mm                      (CPU_FEATURE_CONSTANT(37))
#define cpu_feature_sve_eltperm                    (CPU_FEATURE_CONSTANT(38))
#define cpu_feature_sve_aes2                       (CPU_FEATURE_CONSTANT(39))
#define cpu_feature_sve_bfscale                    (CPU_FEATURE_CONSTANT(40))
#define cpu_feature_sve2p2                         (CPU_FEATURE_CONSTANT(41))
#define cpu_feature_sme2p2                         (CPU_FEATURE_CONSTANT(42))
#define cpu_feature_sme_sbitperm                   (CPU_FEATURE_CONSTANT(43))
#define cpu_feature_sme_aes                        (CPU_FEATURE_CONSTANT(44))
#define cpu_feature_sme_sfexpa                     (CPU_FEATURE_CONSTANT(45))
#define cpu_feature_sme_stmop                      (CPU_FEATURE_CONSTANT(46))
#define cpu_feature_sme_smop4                      (CPU_FEATURE_CONSTANT(47))

// HWCAP2 features (bits 64-95, mapped from HWCAP2 bits 0-31)
#define cpu_feature_dcpodp                         (CPU_FEATURE_CONSTANT(64))
#define cpu_feature_sve2                           (CPU_FEATURE_CONSTANT(65))
#define cpu_feature_sveaes                         (CPU_FEATURE_CONSTANT(66))
#define cpu_feature_svepmull                       (CPU_FEATURE_CONSTANT(67))
#define cpu_feature_svebitperm                     (CPU_FEATURE_CONSTANT(68))
#define cpu_feature_svesha3                        (CPU_FEATURE_CONSTANT(69))
#define cpu_feature_svesm4                         (CPU_FEATURE_CONSTANT(70))
#define cpu_feature_flagm2                         (CPU_FEATURE_CONSTANT(71))
#define cpu_feature_frint                          (CPU_FEATURE_CONSTANT(72))
#define cpu_feature_svei8mm                        (CPU_FEATURE_CONSTANT(73))
#define cpu_feature_svef32mm                       (CPU_FEATURE_CONSTANT(74))
#define cpu_feature_svef64mm                       (CPU_FEATURE_CONSTANT(75))
#define cpu_feature_svebf16                        (CPU_FEATURE_CONSTANT(76))
#define cpu_feature_i8mm                           (CPU_FEATURE_CONSTANT(77))
#define cpu_feature_bf16                           (CPU_FEATURE_CONSTANT(78))
#define cpu_feature_dgh                            (CPU_FEATURE_CONSTANT(79))
#define cpu_feature_rng                            (CPU_FEATURE_CONSTANT(80))
#define cpu_feature_bti                            (CPU_FEATURE_CONSTANT(81))
#define cpu_feature_mte                            (CPU_FEATURE_CONSTANT(82))
#define cpu_feature_ecv                            (CPU_FEATURE_CONSTANT(83))
#define cpu_feature_afp                            (CPU_FEATURE_CONSTANT(84))
#define cpu_feature_rpres                          (CPU_FEATURE_CONSTANT(85))
#define cpu_feature_mte3                           (CPU_FEATURE_CONSTANT(86))
#define cpu_feature_sme                            (CPU_FEATURE_CONSTANT(87))
#define cpu_feature_sme_i16i64                     (CPU_FEATURE_CONSTANT(88))
#define cpu_feature_sme_f64f64                     (CPU_FEATURE_CONSTANT(89))
#define cpu_feature_sme_i8i32                      (CPU_FEATURE_CONSTANT(90))
#define cpu_feature_sme_f16f32                     (CPU_FEATURE_CONSTANT(91))
#define cpu_feature_sme_b16f32                     (CPU_FEATURE_CONSTANT(92))
#define cpu_feature_sme_f32f32                     (CPU_FEATURE_CONSTANT(93))
#define cpu_feature_sme_fa64                       (CPU_FEATURE_CONSTANT(94))
#define cpu_feature_wfxt                           (CPU_FEATURE_CONSTANT(95))

// Extended HWCAP2 features (bits 96-127, mapped from HWCAP2 bits 32-63)
#define cpu_feature_ebf16                          (CPU_FEATURE_CONSTANT(96))
#define cpu_feature_sve_ebf16                      (CPU_FEATURE_CONSTANT(97))
#define cpu_feature_cssc                           (CPU_FEATURE_CONSTANT(98))
#define cpu_feature_rprfm                          (CPU_FEATURE_CONSTANT(99))
#define cpu_feature_sve2p1                         (CPU_FEATURE_CONSTANT(100))
#define cpu_feature_sme2                           (CPU_FEATURE_CONSTANT(101))
#define cpu_feature_sme2p1                         (CPU_FEATURE_CONSTANT(102))
#define cpu_feature_sme_i16i32                     (CPU_FEATURE_CONSTANT(103))
#define cpu_feature_sme_bi32i32                    (CPU_FEATURE_CONSTANT(104))
#define cpu_feature_sme_b16b16                     (CPU_FEATURE_CONSTANT(105))
#define cpu_feature_sme_f16f16                     (CPU_FEATURE_CONSTANT(106))
#define cpu_feature_mops                           (CPU_FEATURE_CONSTANT(107))
#define cpu_feature_hbc                            (CPU_FEATURE_CONSTANT(108))
#define cpu_feature_sve_b16b16                     (CPU_FEATURE_CONSTANT(109))
#define cpu_feature_lrcpc3                         (CPU_FEATURE_CONSTANT(110))
#define cpu_feature_lse128                         (CPU_FEATURE_CONSTANT(111))
#define cpu_feature_fpmr                           (CPU_FEATURE_CONSTANT(112))
#define cpu_feature_lut                            (CPU_FEATURE_CONSTANT(113))
#define cpu_feature_faminmax                       (CPU_FEATURE_CONSTANT(114))
#define cpu_feature_f8cvt                          (CPU_FEATURE_CONSTANT(115))
#define cpu_feature_f8fma                          (CPU_FEATURE_CONSTANT(116))
#define cpu_feature_f8dp4                          (CPU_FEATURE_CONSTANT(117))
#define cpu_feature_f8dp2                          (CPU_FEATURE_CONSTANT(118))
#define cpu_feature_f8e4m3                         (CPU_FEATURE_CONSTANT(119))
#define cpu_feature_f8e5m2                         (CPU_FEATURE_CONSTANT(120))
#define cpu_feature_sme_lutv2                      (CPU_FEATURE_CONSTANT(121))
#define cpu_feature_sme_f8f16                      (CPU_FEATURE_CONSTANT(122))
#define cpu_feature_sme_f8f32                      (CPU_FEATURE_CONSTANT(123))
#define cpu_feature_sme_sf8fma                     (CPU_FEATURE_CONSTANT(124))
#define cpu_feature_sme_sf8dp4                     (CPU_FEATURE_CONSTANT(125))
#define cpu_feature_sme_sf8dp2                     (CPU_FEATURE_CONSTANT(126))
#define cpu_feature_poe                            (CPU_FEATURE_CONSTANT(127))

// CPU architecture baselines
#define cpu_armv8_0_a           (cpu_feature_fp | cpu_feature_asimd)
#define cpu_armv8_1_a           (cpu_armv8_0_a | cpu_feature_atomics | cpu_feature_lrcpc)
#define cpu_armv8_2_a           (cpu_armv8_1_a | cpu_feature_dcpop)
#define cpu_armv8_3_a           (cpu_armv8_2_a | cpu_feature_jscvt | cpu_feature_fcma | cpu_feature_paca | cpu_feature_pacg)
#define cpu_armv8_4_a           (cpu_armv8_3_a | cpu_feature_flagm | cpu_feature_asimddp | cpu_feature_sha512 | cpu_feature_sha3 | cpu_feature_sm3 | cpu_feature_sm4)
#define cpu_armv8_5_a           (cpu_armv8_4_a | cpu_feature_sb | cpu_feature_ssbs)
#define cpu_armv8_6_a           (cpu_armv8_5_a | cpu_feature_bf16 | cpu_feature_i8mm)
#define cpu_armv8_7_a           (cpu_armv8_6_a)
#define cpu_armv8_8_a           (cpu_armv8_7_a)
#define cpu_armv8_9_a           (cpu_armv8_8_a)
#define cpu_armv9_0_a           (cpu_armv8_5_a | cpu_feature_sve | cpu_feature_sve2)
#define cpu_armv9_1_a           (cpu_armv9_0_a | cpu_feature_bf16 | cpu_feature_i8mm)
#define cpu_armv9_2_a           (cpu_armv9_1_a | cpu_feature_mte | cpu_feature_bti)
#define cpu_armv9_3_a           (cpu_armv9_2_a)
#define cpu_armv9_4_a           (cpu_armv9_3_a)

// Common ARM reference cores
#define cpu_neoverse_n1         (cpu_armv8_2_a | cpu_feature_crc32 | cpu_feature_aes | cpu_feature_sha1 | cpu_feature_sha2 | cpu_feature_asimddp)
#define cpu_neoverse_v1         (cpu_armv8_4_a | cpu_feature_crc32 | cpu_feature_aes | cpu_feature_sha1 | cpu_feature_sha2 | cpu_feature_sha512 | cpu_feature_sha3 | cpu_feature_asimddp | cpu_feature_bf16 | cpu_feature_i8mm | cpu_feature_sve)

// Compiler feature detection (compile-time)
static const device_features_t device_compiler_features = 0
#ifdef __ARM_NEON
         | cpu_feature_asimd
#endif
#ifdef __ARM_FEATURE_FP16_SCALAR_ARITHMETIC
         | cpu_feature_fphp
#endif
#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
         | cpu_feature_asimdhp
#endif
#ifdef __ARM_FEATURE_CRYPTO
         | cpu_feature_aes
#endif
#ifdef __ARM_FEATURE_SHA2
         | cpu_feature_sha2
#endif
#ifdef __ARM_FEATURE_PMULL
         | cpu_feature_pmull
#endif
#ifdef __ARM_FEATURE_CRC32
         | cpu_feature_crc32
#endif
#ifdef __ARM_FEATURE_ATOMICS
         | cpu_feature_atomics
#endif
#ifdef __ARM_FEATURE_JCVT
         | cpu_feature_jscvt
#endif
#ifdef __ARM_FEATURE_COMPLEX
         | cpu_feature_fcma
#endif
#ifdef __ARM_FEATURE_RCPC
         | cpu_feature_lrcpc
#endif
#ifdef __ARM_FEATURE_DOTPROD
         | cpu_feature_asimddp
#endif
#ifdef __ARM_FEATURE_RNG
         | cpu_feature_rng
#endif
#ifdef __ARM_FEATURE_SVE
         | cpu_feature_sve
#endif
#ifdef __ARM_FEATURE_SVE2
         | cpu_feature_sve2
#endif
#ifdef __ARM_FEATURE_SVE2_AES
         | cpu_feature_sveaes
#endif
#ifdef __ARM_FEATURE_SVE2_BITPERM
         | cpu_feature_svebitperm
#endif
#ifdef __ARM_FEATURE_SVE2_SHA3
         | cpu_feature_svesha3
#endif
#ifdef __ARM_FEATURE_SVE2_SM4
         | cpu_feature_svesm4
#endif
#ifdef __ARM_FEATURE_BF16
         | cpu_feature_bf16
#endif
#ifdef __ARM_FEATURE_MATMUL_INT8
         | cpu_feature_i8mm
#endif
#ifdef __ARM_FEATURE_SME
         | cpu_feature_sme
#endif
#ifdef __ARM_FEATURE_SME_I16I64
         | cpu_feature_sme_i16i64
#endif
#ifdef __ARM_FEATURE_SME_F64F64
         | cpu_feature_sme_f64f64
#endif
#ifdef __ARM_FEATURE_MEMORY_TAGGING
         | cpu_feature_mte
#endif
#ifdef __ARM_FEATURE_BTI
         | cpu_feature_bti
#endif
         ;

// Feature string table
static const char features_string[] =
    " fp\0"
    " asimd\0"
    " evtstrm\0"
    " aes\0"
    " pmull\0"
    " sha1\0"
    " sha2\0"
    " crc32\0"
    " atomics\0"
    " fphp\0"
    " asimdhp\0"
    " cpuid\0"
    " asimdrdm\0"
    " jscvt\0"
    " fcma\0"
    " lrcpc\0"
    " dcpop\0"
    " sha3\0"
    " sm3\0"
    " sm4\0"
    " asimddp\0"
    " sha512\0"
    " sve\0"
    " asimdfhm\0"
    " dit\0"
    " uscat\0"
    " ilrcpc\0"
    " flagm\0"
    " ssbs\0"
    " sb\0"
    " paca\0"
    " pacg\0"
    " gcs\0"
    " cmpbr\0"
    " fprcvt\0"
    " f8mm8\0"
    " f8mm4\0"
    " sve_f16mm\0"
    " sve_eltperm\0"
    " sve_aes2\0"
    " sve_bfscale\0"
    " sve2p2\0"
    " sme2p2\0"
    " sme_sbitperm\0"
    " sme_aes\0"
    " sme_sfexpa\0"
    " sme_stmop\0"
    " sme_smop4\0"
    " dcpodp\0"
    " sve2\0"
    " sveaes\0"
    " svepmull\0"
    " svebitperm\0"
    " svesha3\0"
    " svesm4\0"
    " flagm2\0"
    " frint\0"
    " svei8mm\0"
    " svef32mm\0"
    " svef64mm\0"
    " svebf16\0"
    " i8mm\0"
    " bf16\0"
    " dgh\0"
    " rng\0"
    " bti\0"
    " mte\0"
    " ecv\0"
    " afp\0"
    " rpres\0"
    " mte3\0"
    " sme\0"
    " sme_i16i64\0"
    " sme_f64f64\0"
    " sme_i8i32\0"
    " sme_f16f32\0"
    " sme_b16f32\0"
    " sme_f32f32\0"
    " sme_fa64\0"
    " wfxt\0"
    " ebf16\0"
    " sve_ebf16\0"
    " cssc\0"
    " rprfm\0"
    " sve2p1\0"
    " sme2\0"
    " sme2p1\0"
    " sme_i16i32\0"
    " sme_bi32i32\0"
    " sme_b16b16\0"
    " sme_f16f16\0"
    " mops\0"
    " hbc\0"
    " sve_b16b16\0"
    " lrcpc3\0"
    " lse128\0"
    " fpmr\0"
    " lut\0"
    " faminmax\0"
    " f8cvt\0"
    " f8fma\0"
    " f8dp4\0"
    " f8dp2\0"
    " f8e4m3\0"
    " f8e5m2\0"
    " sme_lutv2\0"
    " sme_f8f16\0"
    " sme_f8f32\0"
    " sme_sf8fma\0"
    " sme_sf8dp4\0"
    " sme_sf8dp2\0"
    " poe\0"
    "\0";

// Feature index sentinel for unused/reserved HWCAP bit positions
#define FEATURE_INDEX_UNUSED    911

// Features 48-63 are reserved/unused in HWCAP, FEATURE_INDEX_UNUSED marks these gaps
static const uint16_t features_indices[] = {
       0,    4,   11,   20,   25,   32,   38,   44,
      51,   60,   66,   75,   82,   92,   99,  105,
     112,  119,  125,  130,  135,  144,  152,  157,
     167,  172,  179,  187,  194,  200,  204,  210,
     216,  221,  228,  236,  243,  250,  261,  274,
     284,  297,  305,  313,  327,  336,  348,  359,
     911,  911,  911,  911,  911,  911,  911,  911,
     911,  911,  911,  911,  911,  911,  911,  911,
     370,  378,  384,  392,  402,  414,  423,  431,
     439,  446,  455,  465,  475,  484,  490,  496,
     501,  506,  511,  516,  521,  526,  533,  539,
     544,  556,  568,  579,  591,  603,  615,  625,
     631,  638,  649,  655,  662,  670,  676,  684,
     696,  709,  721,  733,  739,  744,  756,  764,
     772,  778,  783,  793,  800,  807,  814,  821,
     829,  837,  848,  859,  870,  882,  894,  906,
};

// HWCAP mapping for runtime detection
// Array index is the feature bit position in device_features_t
// Array value is the HWCAP/HWCAP2 bit position
// Features 0-63 map to HWCAP bits 0-63, features 64-127 map to HWCAP2 bits 0-63
static const uint8_t aarch64_locators[] = {
    // HWCAP bits 0-63
     0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
    16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
    32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
    48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
    // HWCAP2 bits 0-63
     0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
    16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
    32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
    48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
};

// Architecture identification
struct AArch64Architecture {
    device_features_t features;
    char name[24];
};

static const struct AArch64Architecture aarch64_architectures[] = {
    // Most feature-rich first (for best-match detection)
    { cpu_armv9_4_a, "ARMv9.4-A" },
    { cpu_armv9_3_a, "ARMv9.3-A" },
    { cpu_armv9_2_a, "ARMv9.2-A" },
    { cpu_armv9_1_a, "ARMv9.1-A" },
    { cpu_armv9_0_a, "ARMv9.0-A" },
    { cpu_armv8_9_a, "ARMv8.9-A" },
    { cpu_armv8_8_a, "ARMv8.8-A" },
    { cpu_armv8_7_a, "ARMv8.7-A" },
    { cpu_armv8_6_a, "ARMv8.6-A" },
    { cpu_armv8_5_a, "ARMv8.5-A" },
    { cpu_armv8_4_a, "ARMv8.4-A" },
    { cpu_armv8_3_a, "ARMv8.3-A" },
    { cpu_armv8_2_a, "ARMv8.2-A" },
    { cpu_armv8_1_a, "ARMv8.1-A" },
    { cpu_armv8_0_a, "ARMv8.0-A" },
    // ARM reference cores
    { cpu_neoverse_v1, "Neoverse V1" },
    { cpu_neoverse_n1, "Neoverse N1" },
};

// Not an ARM feature: kept for build compatibility with x86.
// The logging code uses this flag to detect whether it's running in a VM.
// An equivalent ARM VM-detection mechanism is required, but that work is
// out of scope for now. We use bit 63 which the Linux kernel guarantees is
// always returned as 0 in AT_HWCAP (see arm64 ELF hwcaps documentation,
// "Unused AT_HWCAP bits" - bits 62 and 63 are reserved). detect_cpu() never
// sets this bit, so device_has_feature(cpu_feature_hypervisor) will always
// return false (bare metal).
#define cpu_feature_hypervisor  (((device_features_t) 1) << 63)

// AArch64 CPU vendor and part number identification using Main ID
// Register (MIDR_EL1).
// Reference:
//   https://developer.arm.com/documentation/ddi0601/2025-03/AArch64-Registers/MIDR-EL1--Main-ID-Register

#define ARRAY_SIZE(arr) (sizeof(arr) / sizeof((arr)[0]))

//  MIDR_EL1
//
//  Bit # |31         24|23     20|19          16|15          4|3        0|
//  Value | Implementer | Variant | Architecture | Part Number | Revision |

#define MIDR_EL1_IMPLEMENTER(midr_el1)  ((uint8_t) (((uint32_t)(midr_el1) & 0xFF000000U) >> 24))
#define MIDR_EL1_VARIANT(midr_el1)      ((uint8_t) (((uint32_t)(midr_el1) & 0x00F00000U) >> 20))
// The ARCHITECTURE value is not used in the code. It is included for completeness.
// #define MIDR_EL1_ARCHITECTURE(midr_el1) ((uint8_t) (((uint32_t)(midr_el1) & 0x000F0000U) >> 16))
#define MIDR_EL1_PART_NUM(midr_el1)     ((uint16_t)(((uint32_t)(midr_el1) & 0x0000FFF0U) >>  4))
#define MIDR_EL1_REVISION(midr_el1)     ((uint8_t) (((uint32_t)(midr_el1) & 0x0000000FU)      ))

// Instantiate this for each implementer
struct VendorParts {
    uint16_t part_num;
    const char *name;
};

// Qualcomm parts
static const struct VendorParts qcomm_parts[] = {
    { 0x001, "Oryon(TM) CPU (Gen 1/Gen 2)" },
    { 0x002, "Oryon(TM) CPU (Gen 3)" },
    { 0x003, "Oryon(TM) CPU (Gen 4)" },
    { 0x004, "Oryon(TM) CPU (Gen 5)" },
};

struct Vendor {
    uint8_t id;
    const char *name;
    const struct VendorParts *parts;
    size_t num_parts;
};

static const struct Vendor aarch64_vendors[] = {
    { 0x00, "Reserved for software use", NULL, 0 },
    { 0x41, "Arm Limited", NULL, 0 },
    { 0x42, "Broadcom Corporation", NULL, 0 },
    { 0x43, "Cavium Inc.", NULL, 0 },
    { 0x44, "Digital Equipment Corporation", NULL, 0 },
    { 0x46, "Fujitsu Ltd.", NULL, 0 },
    { 0x49, "Infineon Technologies AG", NULL, 0 },
    { 0x4D, "Motorola or Freescale Semiconductor Inc.", NULL, 0 },
    { 0x4E, "NVIDIA Corporation", NULL, 0 },
    { 0x50, "Applied Micro Circuits Corporation", NULL, 0 },
    { 0x51, "Qualcomm Inc.", qcomm_parts, sizeof(qcomm_parts) / sizeof(qcomm_parts[0]) },
    { 0x56, "Marvell International Ltd.", NULL, 0 },
    { 0x69, "Intel Corporation", NULL, 0 },
    { 0xC0, "Ampere Computing", NULL, 0 }
};

#endif /* INC_CPU_FEATURES_AARCH64_H */
