name: Pull Request

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ main ]

env:
  GIT_CONFIG_SYSTEM: /tmp/gitconfig

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
    - name: Install distro packages
      run: |
        DEBIAN_FRONTEND=noninteractive apt-get -y update
        DEBIAN_FRONTEND=noninteractive apt-get -y install \
            bats \
            elfutils \
            file \
            git \
            libboost-dev \
            libeigen3-dev \
            libgtest-dev \
            libzstd-dev \
            meson \
            ninja-build \
            python3-yaml \
            zlib1g-dev
    - uses: actions/checkout@v2
    - name: setup Git
      run: git config --system safe.directory '*'
    - name: meson setup -Dbuildtype=debugoptimized
      run: meson setup builddir
    - name: ninja build
      run: ninja -C builddir
    - name: ninja build unittests
      run: ninja -C builddir unittests
    - name: run unittests
      run: |
        ./builddir/unittests \
          --gtest_filter=-LinuxThermalFixture.CurrentMachine_TestUsingSingletomTemperaturesOnCurrentMachine # this test doesn't execute properly in a github runner
    - name: run selftests
      run: |
        ulimit -St 120
        SANDSTONE_BIN=builddir/opendcdiag bats -t bats/sanity-check

  build-windows:
    runs-on: ubuntu-latest
    container: fedora:34
    steps:
    - name: Install distro packages
      run: |
        dnf install -y \
            cmake \
            git \
            meson \
            mingw64-boost-static \
            mingw64-eigen3 \
            mingw64-gcc-c++ \
            mingw64-pixman-static \
            mingw64-pkg-config \
            mingw64-winpthreads-static \
            mingw64-zstd \
            perl
    - uses: actions/checkout@v2
    - name: setup Git
      run: git config --system safe.directory '*'
    - name: meson setup
      run: meson setup builddir-windows-cross --cross-file meson-cross-win32.ini
    - name: ninja build
      run: ninja -C builddir-windows-cross
